name: Merge

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  delete-preview-link:
    if: github.event.pull_request.merged == true
    
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          rm -rf pr-${{ github.event.number }}
          git add .
          git commit -m "remove pr-${{ github.event.number }}"
          git push